version: '3'
services:
  db:
    image: 'postgres:latest'
    restart: unless-stopped
    volumes:
      - ./be/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - TZ=Asiz/Seoul
    ports:
      - 5432:5432
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis_boot
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - .db/mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root 
      - MONGO_INITDB_DATABASE=blog